# Concept

New approach is to use df.apply(func) to extract financial data and process it for Financial Ratios calculation for better computation efficiency (lower computation load, higher speed).

Financial ratios are split into numerator and denominator of different financial data sets in general.

In [1]:
import pandas as pd
from pandas import Series, DataFrame

import numpy as np

In [2]:
df_input = pd.read_excel("uniqueItemsFromAnnualReports_AEON_Retail_M3.xlsx", sheet_name = "Main", index_col = 0)

In [3]:
# df_input.drop("Source Document", axis = 1, inplace = True)

In [4]:
df_input

2019          2018  \
Items                                                                   
Gross Dividend Payout (Currency per Unit)  4.000000e-02  4.000000e-02   
Outstanding Shares                         1.401380e+09  1.403038e+09   
Unit Price (Currency)                      1.420000e+00  1.470000e+00   
Total Interest Paid                        1.677510e+05  4.293500e+04   
Trade Debtors                              8.777210e+05  8.409470e+05   
Trade Creditors                            2.640500e+04  3.692900e+04   
Sales                                      3.352845e+06  3.211008e+06   
Cash and Cash Equivalent                   6.698200e+04  8.215400e+04   
Free Cash Flow                            -1.517200e+04  3.560000e+03   
Net Cash Flow from Financing              -4.338330e+05 -4.205100e+04   
Net Cash Flow from Investments            -2.704400e+05 -5.181510e+05   
Net Cash Flow from Operations              6.891010e+05  5.637620e+05   
Current Assets                             8.904810e+05  8.307700e+05   
Current Liabilities                        2.470228e+06  2.258437e+06   
Fixed Assets                               3.647203e+06  3.699455e+06   
Intangible Assets                          1.198000e+04  1.417900e+04   
Shareholders Equity                        1.695670e+06  2.020375e+06   
Stock                                      7.540720e+05  6.801400e+05   
Total Assets                               6.537774e+06  4.646706e+06   
Total Debt                                 9.286600e+05  9.954230e+05   
Total Liabilities                          4.842104e+06  2.626331e+06   
Amortization                               6.243000e+03  6.191000e+03   
Cost of Goods Sold                         2.757139e+06  2.661816e+06   
Depreciation                               4.785550e+05  2.978070e+05   
Interest Expense                           1.629270e+05  4.293500e+04   
Net Income                                 1.092920e+05  1.051230e+05   
Operating Expense                          6.908180e+05  9.179600e+05   
Operating Profit                           3.587230e+05  2.396900e+05   
Personnel Expense                          3.303400e+05  3.079990e+05   
Revenue                                    4.538884e+06  4.353640e+06   
Tax                                        8.759500e+04  8.191500e+04   
Total Expenses                             3.941224e+06  3.930710e+06   

                                                   2017          2016  \
Items                                                                   
Gross Dividend Payout (Currency per Unit)  4.000000e-02  3.000000e-02   
Outstanding Shares                         1.402048e+09  1.404426e+09   
Unit Price (Currency)                      1.760000e+00  2.570000e+00   
Total Interest Paid                        3.921200e+04  3.659900e+04   
Trade Debtors                              7.762120e+05  7.680330e+05   
Trade Creditors                            7.553000e+04  5.147700e+04   
Sales                                      3.035686e+06  3.019156e+06   
Cash and Cash Equivalent                   7.859400e+04  8.148800e+04   
Free Cash Flow                            -2.894000e+03 -1.093210e+05   
Net Cash Flow from Financing              -1.090540e+05  1.027610e+05   
Net Cash Flow from Investments            -2.790750e+05 -6.946500e+05   
Net Cash Flow from Operations              3.852350e+05  4.825680e+05   
Current Assets                             7.781740e+05  8.398140e+05   
Current Liabilities                        2.625845e+06  2.170979e+06   
Fixed Assets                               3.504045e+06  3.436077e+06   
Intangible Assets                          1.722800e+04  1.962700e+04   
Shareholders Equity                        1.962867e+06  1.881931e+06   
Stock                                      6.107310e+05  6.022830e+05   
Total Assets                               4.409564e+06  4.413716e+06   
Total Debt                         

In [5]:
financialYears = df_input.columns.values

In [6]:
import itertools

column_names =  list(itertools.chain(["Financial Ratios"], financialYears))

In [7]:
df_financialRatios = pd.DataFrame(columns = column_names)
df_financialRatios

Empty DataFrame
Columns: [Financial Ratios, 2019, 2018, 2017, 2016, 2015]
Index: []

In [8]:
# Read Row for Financial Ratios calculation
def read_row(row):
    print(row, type(row))
    print(row.name)
    print(row.index)
    print(row.values)
    
    return row


In [9]:
df_input_row = df_input.loc[["Unit Price (Currency)"]].apply(read_row, axis = 1)

2019    1.42
2018    1.47
2017    1.76
2016    2.57
2015    2.73
Name: Unit Price (Currency), dtype: float64 <class 'pandas.core.series.Series'>
Unit Price (Currency)
Int64Index([2019, 2018, 2017, 2016, 2015], dtype='int64')
[1.42 1.47 1.76 2.57 2.73]


In [10]:
df_input_row

2019  2018  2017  2016  2015
Items                                              
Unit Price (Currency)  1.42  1.47  1.76  2.57  2.73

In [11]:
df_input.loc[["Unit Price (Currency)", "Outstanding Shares"]]

2019          2018          2017          2016  \
Items                                                                           
Unit Price (Currency)  1.420000e+00  1.470000e+00  1.760000e+00  2.570000e+00   
Outstanding Shares     1.401380e+09  1.403038e+09  1.402048e+09  1.404426e+09   

                               2015  
Items                                
Unit Price (Currency)  2.730000e+00  
Outstanding Shares     1.399694e+09

In [12]:
ser_processing = df_input.loc[["Unit Price (Currency)", "Outstanding Shares"]].apply(read_row, axis = 1)

2019    1.42
2018    1.47
2017    1.76
2016    2.57
2015    2.73
Name: Unit Price (Currency), dtype: float64 <class 'pandas.core.series.Series'>
Unit Price (Currency)
Int64Index([2019, 2018, 2017, 2016, 2015], dtype='int64')
[1.42 1.47 1.76 2.57 2.73]
2019    1.401380e+09
2018    1.403038e+09
2017    1.402048e+09
2016    1.404426e+09
2015    1.399694e+09
Name: Outstanding Shares, dtype: float64 <class 'pandas.core.series.Series'>
Outstanding Shares
Int64Index([2019, 2018, 2017, 2016, 2015], dtype='int64')
[1.40138017e+09 1.40303820e+09 1.40204786e+09 1.40442612e+09
 1.39969389e+09]


In [13]:
ser_processing

2019          2018          2017          2016  \
Items                                                                           
Unit Price (Currency)  1.420000e+00  1.470000e+00  1.760000e+00  2.570000e+00   
Outstanding Shares     1.401380e+09  1.403038e+09  1.402048e+09  1.404426e+09   

                               2015  
Items                                
Unit Price (Currency)  2.730000e+00  
Outstanding Shares     1.399694e+09

In [14]:
type(ser_processing)

pandas.core.frame.DataFrame

In [15]:
# print(ser_processing.name)

In [16]:
print(ser_processing.values)

[[1.42000000e+00 1.47000000e+00 1.76000000e+00 2.57000000e+00
  2.73000000e+00]
 [1.40138017e+09 1.40303820e+09 1.40204786e+09 1.40442612e+09
  1.39969389e+09]]


In [17]:
print(ser_processing.index)

Index(['Unit Price (Currency)', 'Outstanding Shares'], dtype='object', name='Items')


In [18]:
# Read Row
arr_unitPrice = df_input.loc["Unit Price (Currency)"].values

In [19]:
arr_outstandingShares = df_input.loc["Outstanding Shares"].values

In [20]:
arr_marketCap = (arr_unitPrice * arr_outstandingShares) / 1000

In [21]:
arr_marketCap 

array([1989959.83572, 2062466.14665, 2467604.23008, 3609375.1284 ,
       3821164.33062])

In [22]:
arr_totAssets = df_input.loc["Total Assets"].values
arr_intAssets = df_input.loc["Intangible Assets"].values
arr_totLiabilities = df_input.loc["Total Liabilities"].values

arr_bookVal = arr_totAssets - arr_intAssets - arr_totLiabilities
arr_bookVal

array([1683690., 2006196., 1945639., 1862304., 1826141.])

In [23]:
arr_PE = arr_marketCap/arr_bookVal

In [24]:
df_financialRatios = df_financialRatios.append({"Financial Ratios": "Price to Book Ratio"}, ignore_index = True, sort = False)

In [25]:
df_financialRatios

Financial Ratios 2019 2018 2017 2016 2015
0  Price to Book Ratio  NaN  NaN  NaN  NaN  NaN

In [26]:
# Write to df_FinancialRatios
for index, item in enumerate(arr_PE):
    # print(index, item)
    df_financialRatios.loc[df_financialRatios[df_financialRatios.columns[0]] == "Price to Book Ratio", financialYears[index]] = item

df_financialRatios

Financial Ratios      2019      2018      2017      2016     2015
0  Price to Book Ratio  1.181904  1.028048  1.268274  1.938123  2.09248

In [27]:
(df_input.loc["Gross Dividend Payout (Currency per Unit)"].values).any()

True

### Test Region for financialRatios module

In [28]:
from financialRatiosModule.financialRatios import financialData_main

In [29]:
AEON = financialData_main("uniqueItemsFromAnnualReports_AEON_Retail_M3.xlsx", "Main", 0)

Financial Data Object created


In [30]:
AEON.getInput()

2019          2018  \
Items                                                                   
Gross Dividend Payout (Currency per Unit)  4.000000e-02  4.000000e-02   
Outstanding Shares                         1.401380e+09  1.403038e+09   
Unit Price (Currency)                      1.420000e+00  1.470000e+00   
Total Interest Paid                        1.677510e+05  4.293500e+04   
Trade Debtors                              8.777210e+05  8.409470e+05   
Trade Creditors                            2.640500e+04  3.692900e+04   
Sales                                      3.352845e+06  3.211008e+06   
Cash and Cash Equivalent                   6.698200e+04  8.215400e+04   
Free Cash Flow                            -1.517200e+04  3.560000e+03   
Net Cash Flow from Financing              -4.338330e+05 -4.205100e+04   
Net Cash Flow from Investments            -2.704400e+05 -5.181510e+05   
Net Cash Flow from Operations              6.891010e+05  5.637620e+05   
Current Assets                             8.904810e+05  8.307700e+05   
Current Liabilities                        2.470228e+06  2.258437e+06   
Fixed Assets                               3.647203e+06  3.699455e+06   
Intangible Assets                          1.198000e+04  1.417900e+04   
Shareholders Equity                        1.695670e+06  2.020375e+06   
Stock                                      7.540720e+05  6.801400e+05   
Total Assets                               6.537774e+06  4.646706e+06   
Total Debt                                 9.286600e+05  9.954230e+05   
Total Liabilities                          4.842104e+06  2.626331e+06   
Amortization                               6.243000e+03  6.191000e+03   
Cost of Goods Sold                         2.757139e+06  2.661816e+06   
Depreciation                               4.785550e+05  2.978070e+05   
Interest Expense                           1.629270e+05  4.293500e+04   
Net Income                                 1.092920e+05  1.051230e+05   
Operating Expense                          6.908180e+05  9.179600e+05   
Operating Profit                           3.587230e+05  2.396900e+05   
Personnel Expense                          3.303400e+05  3.079990e+05   
Revenue                                    4.538884e+06  4.353640e+06   
Tax                                        8.759500e+04  8.191500e+04   
Total Expenses                             3.941224e+06  3.930710e+06   

                                                   2017          2016  \
Items                                                                   
Gross Dividend Payout (Currency per Unit)  4.000000e-02  3.000000e-02   
Outstanding Shares                         1.402048e+09  1.404426e+09   
Unit Price (Currency)                      1.760000e+00  2.570000e+00   
Total Interest Paid                        3.921200e+04  3.659900e+04   
Trade Debtors                              7.762120e+05  7.680330e+05   
Trade Creditors                            7.553000e+04  5.147700e+04   
Sales                                      3.035686e+06  3.019156e+06   
Cash and Cash Equivalent                   7.859400e+04  8.148800e+04   
Free Cash Flow                            -2.894000e+03 -1.093210e+05   
Net Cash Flow from Financing              -1.090540e+05  1.027610e+05   
Net Cash Flow from Investments            -2.790750e+05 -6.946500e+05   
Net Cash Flow from Operations              3.852350e+05  4.825680e+05   
Current Assets                             7.781740e+05  8.398140e+05   
Current Liabilities                        2.625845e+06  2.170979e+06   
Fixed Assets                               3.504045e+06  3.436077e+06   
Intangible Assets                          1.722800e+04  1.962700e+04   
Shareholders Equity                        1.962867e+06  1.881931e+06   
Stock                                      6.107310e+05  6.022830e+05   
Total Assets                               4.409564e+06  4.413716e+06   
Total Debt                         

In [31]:
AEON.getFinancialRatios()

Empty DataFrame
Columns: [Financial Ratios, 2019, 2018, 2017, 2016, 2015]
Index: []

In [32]:
AEON.getFinancialYears()

array([2019, 2018, 2017, 2016, 2015], dtype=int64)

In [33]:
AEON.getFinancialData_row("Unit Price (Currency)")

array([1.42, 1.47, 1.76, 2.57, 2.73])

In [34]:
marketCap = ( AEON.getFinancialData_row("Unit Price (Currency)") * AEON.getFinancialData_row("Outstanding Shares") ) / 1000
marketCap

array([1989959.83572, 2062466.14665, 2467604.23008, 3609375.1284 ,
       3821164.33062])

In [35]:
bookVal = AEON.getFinancialData_row("Total Assets") - AEON.getFinancialData_row("Total Liabilities")- AEON.getFinancialData_row("Intangible Assets")
bookVal

array([1683690., 2006196., 1945639., 1862304., 1826141.])

In [36]:
PtE_ratio = marketCap/bookVal
PtE_ratio

array([1.18190393, 1.02804818, 1.26827445, 1.93812349, 2.09248044])

In [37]:
AEON.setFinancialRatios_row("Price to Book Ratio", PtE_ratio)

In [38]:
AEON.getFinancialRatios()

Financial Ratios      2019      2018      2017      2016     2015
0  Price to Book Ratio  1.181904  1.028048  1.268274  1.938123  2.09248

In [39]:
AEON.getFinancialRatios().set_index(AEON.getFinancialRatios().columns[0])

2019      2018      2017      2016     2015
Financial Ratios                                                    
Price to Book Ratio  1.181904  1.028048  1.268274  1.938123  2.09248

In [40]:
from financialRatiosModule.FR_Valuation import valuation_gen

In [41]:
AEON = valuation_gen("uniqueItemsFromAnnualReports_AEON_Retail_M3.xlsx", "Main", 0)

Financial Data Object created


In [42]:
AEON.analyzeValuation()

Analyzing Valuation


In [43]:
AEON.getFinancialRatios()

Financial Ratios       2019       2018       2017       2016  \
0      Price to Book Ratio   1.181904   1.028048   1.268274   1.938123   
1  Price to Earnings Ratio  18.207736  19.619552  23.499426  39.710592   

        2015  
0    2.09248  
1  29.020546

In [44]:
from financialRatiosModule.Sector_Retail import financialData_retail

In [45]:
AEON = financialData_retail("uniqueItemsFromAnnualReports_AEON_Retail_M3.xlsx", "Main", 0)

Financial Data Object created


In [46]:
AEON.analyze_retail()

Analyzing Retail Sector's Financial Ratios
Analyzing Valuation
Analyzing Profitability
Analyze Efficiency
Analyzing Liquidity Ratios
Analyzing Solvency
Analyzing Dividend Financial Ratios
Dividend data found
Analyzing Sales-related Financial Ratios
Sales data available
Analyze Inventory Holding
Stock data found.


In [47]:
AEON.getFinancialRatios()

Financial Ratios        2019       2018       2017  \
0               Price to Book Ratio    1.181904   1.028048   1.268274   
1           Price to Earnings Ratio   18.207736  19.619552  23.499426   
2                  Return on Equity    0.064454   0.052031   0.053497   
3        Return on Capital Employed    0.088192   0.100361   0.134854   
4           EBITDA to Revenue Ratio    0.186084   0.122649   0.128612   
5   EBITDA to Cash Conversion Ratio    0.815879   1.055791   0.732683   
6          Revenue to Expense Ratio    1.151643   1.107596   1.134005   
7                     Current Ratio    0.360485   0.367852   0.296352   
8                        Cash Ratio    0.027116   0.036376   0.029931   
9         Operating Cash Flow Ratio    0.278963   0.249625   0.146709   
10            Cash Conversion Ratio    6.305137    5.36288    3.66866   
11                       Debt Ratio    0.142045   0.214221   0.212645   
12             Debt to Equity Ratio    0.547666   0.492692   0.477704   
13          Interest Coverage Ratio     5.18399   12.43673  12.903065   
14              Years to Repay Debt    1.099511   1.864189   1.783365   
15            Average Interest Rate    0.175443   0.043132   0.043458   
16                   Dividend Yield    0.028169   0.027211   0.022727   
17          Dividend Coverage Ratio    1.949721   1.873131   1.872386   
18            Dividend Payout Ratio    0.512894   0.533865   0.534078   
19                     Gross Margin    0.531413   0.526883   0.557947   
20             Capital Productivity    0.106991   0.074646   0.079238   
21                    COGS per Sale    0.822328   0.828966   0.788755   
22      Working Capital Producitivy   -2.122394   -2.24913   -1.64298   
23       Trade Debtors Productivity    3.819944   3.818324   3.910898   
24               Trade Debtors Days   95.551141  95.591682  93.328948   
25     Trade Creditors Productivity  126.977656  86.950852  40.191791   
26             Trade Creditors Days    2.874521   4.197774   9.081456   
27        Fixed Assets Productivity    0.919292   0.867968   0.866338   
28                       Stock Days    99.82677  93.263809  93.098771   
29                   Stock Turnover    4.446319   4.721099   4.970578   
30                      Quick Ratio    0.055221   0.066697   0.063767   

         2016       2015  
0    1.938123    2.09248  
1   39.710592  29.020546  
2    0.048297   0.071813  
3    0.088108   0.116312  
4    0.115419   0.116368  
5    1.040392   0.665242  
6    1.105164   1.102995  
7    0.386837   0.445625  
8    0.037535   0.102291  
9    0.222281   0.141988  
10   5.309246    2.25449  
11   0.218725   0.190454  
12   0.512979    0.41738  
13  12.548236  24.183286  
14   2.081335   1.725281  
15   0.038289   0.023968  
16   0.011673   0.014652  
17   2.157275   2.351782  
18   0.463548   0.425209  
19   0.513865   0.496939  
20    0.06545   0.078362  
21   0.817198   0.826818  
22  -2.268055   -2.49934  
23   3.931024   4.123432  
24   92.85113  88.518502  
25  58.650582  60.782765  
26   6.223297   6.004992  
27   0.878664   0.955375  
28  89.100607  88.009884  
29   5.012853    5.01593  
30   0.109412   0.169391

In [48]:
AEON.writeOut("FR_AEON_retail")

In [49]:
AEON.getFinancialRatios()

2019       2018       2017       2016  \
Financial Ratios                                                               
Price to Book Ratio                1.181904   1.028048   1.268274   1.938123   
Price to Earnings Ratio           18.207736  19.619552  23.499426  39.710592   
Return on Equity                   0.064454   0.052031   0.053497   0.048297   
Return on Capital Employed         0.088192   0.100361   0.134854   0.088108   
EBITDA to Revenue Ratio            0.186084   0.122649   0.128612   0.115419   
EBITDA to Cash Conversion Ratio    0.815879   1.055791   0.732683   1.040392   
Revenue to Expense Ratio           1.151643   1.107596   1.134005   1.105164   
Current Ratio                      0.360485   0.367852   0.296352   0.386837   
Cash Ratio                         0.027116   0.036376   0.029931   0.037535   
Operating Cash Flow Ratio          0.278963   0.249625   0.146709   0.222281   
Cash Conversion Ratio              6.305137    5.36288    3.66866   5.309246   
Debt Ratio                         0.142045   0.214221   0.212645   0.218725   
Debt to Equity Ratio               0.547666   0.492692   0.477704   0.512979   
Interest Coverage Ratio             5.18399   12.43673  12.903065  12.548236   
Years to Repay Debt                1.099511   1.864189   1.783365   2.081335   
Average Interest Rate              0.175443   0.043132   0.043458   0.038289   
Dividend Yield                     0.028169   0.027211   0.022727   0.011673   
Dividend Coverage Ratio            1.949721   1.873131   1.872386   2.157275   
Dividend Payout Ratio              0.512894   0.533865   0.534078   0.463548   
Gross Margin                       0.531413   0.526883   0.557947   0.513865   
Capital Productivity               0.106991   0.074646   0.079238    0.06545   
COGS per Sale                      0.822328   0.828966   0.788755   0.817198   
Working Capital Producitivy       -2.122394   -2.24913   -1.64298  -2.268055   
Trade Debtors Productivity         3.819944   3.818324   3.910898   3.931024   
Trade Debtors Days                95.551141  95.591682  93.328948   92.85113   
Trade Creditors Productivity     126.977656  86.950852  40.191791  58.650582   
Trade Creditors Days               2.874521   4.197774   9.081456   6.223297   
Fixed Assets Productivity          0.919292   0.867968   0.866338   0.878664   
Stock Days                         99.82677  93.263809  93.098771  89.100607   
Stock Turnover                     4.446319   4.721099   4.970578   5.012853   
Quick Ratio                        0.055221   0.066697   0.063767   0.109412   

                                      2015  
Financial Ratios                            
Price to Book Ratio                2.09248  
Price to Earnings Ratio          29.020546  
Return on Equity                  0.071813  
Return on Capital Employed        0.116312  
EBITDA to Revenue Ratio           0.116368  
EBITDA to Cash Conversion Ratio   0.665242  
Revenue to Expense Ratio          1.102995  
Current Ratio                     0.445625  
Cash Ratio                        0.102291  
Operating Cash Flow Ratio         0.141988  
Cash Conversion Ratio              2.25449  
Debt Ratio                        0.190454  
Debt to Equity Ratio               0.41738  
Interest Coverage Ratio          24.183286  
Years to Repay Debt               1.725281  
Average Interest Rate             0.023968  
Dividend Yield                    0.014652  
Dividend Coverage Ratio           2.351782  
Dividend Payout Ratio             0.425209  
Gross Margin                      0.496939  
Capital Productivity              0.078362  
COGS per Sale                     0.826818  
Working Capital Producitivy       -2.49934  
Trade Debtors Productivity        4.123432  
Trade Debtors Days               88.518502  
Trade Creditors Productivity     60.782765  
Trade Creditors Days              6.004992  
Fixed Assets Productivity         0.955375  
Stock Days                       88.009884  
Sto